version: '3.4'

networks:
    productnetwork:

services:
  productdb:
    container_name: productdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment: 
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Inovation123$
    networks:
     - productnetwork
  productsystem:
    container_name: productsystem
    ports:
    - 8001:80 
    image: ${DOCKER_REGISTRY-}productsystem
    build:
      context: .
      dockerfile: ProductSystem/Dockerfile
    depends_on:
    - productdb
    networks:
    - productnetwork



